import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  introductionSidebar: [{type: 'autogenerated', dirName: 'introduction'}],
  eftSidebar: [
    'eft-turkish-banks/intro',
    'eft-turkish-banks/eft-flow',
    'eft-turkish-banks/create-eft',
    'eft-turkish-banks/check-eft-status',
    'eft-turkish-banks/get-eft-list',
    'eft-turkish-banks/get-refund-list',
    'eft-turkish-banks/cancel-eft',
    'eft-turkish-banks/webhooks',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'eft-turkish-banks/exchange',
    'eft-turkish-banks/validate-iban',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'eft-turkish-banks/error-codes',
  ],
  qrPaymentsSidebar: [
    'qr-payments/intro',
    'qr-payments/read-qr',
    'qr-payments/confirm-payment',
    'qr-payments/webhooks',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'qr-payments/mock-api',
  ],
  moneyTransfersSidebar: [
    'money-transfers/intro',
    {
      type: 'category',
      label: 'To Name (Cash Pick Up)',
      link: {
        type: 'generated-index',
        description: 'Send money that can be collected in cash from PayPorter offices or partner locations.',
      },
      items: [
        'money-transfers/to-name/overview',
        'money-transfers/to-name/find-firm',
        'money-transfers/to-name/find-city',
        'money-transfers/to-name/find-office',
        'money-transfers/to-name/validate',
        'money-transfers/to-name/confirm',
      ],
    },
    {
      type: 'category',
      label: 'To Bank Account',
      link: {
        type: 'generated-index',
        description: 'Direct transfer to a bank account or IBAN.',
      },
      items: [
        'money-transfers/to-account/validate',
        'money-transfers/to-account/confirm',
      ],
    },
    {
      type: 'category',
      label: 'To Wallet',
      link: {
        type: 'generated-index',
        description: 'Send funds to a recipient\'s electronic wallet.',
      },
      items: [
        'money-transfers/to-wallet/validate',
        'money-transfers/to-wallet/confirm',
      ],
    },
    {
      type: 'category',
      label: 'To Card',
      link: {
        type: 'generated-index',
        description: 'Transfer directly to a debit or credit card.',
      },
      items: [
        'money-transfers/to-card/validate',
        'money-transfers/to-card/confirm',
      ],
    },
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'money-transfers/transfer-details',
    'money-transfers/fields-api',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
