import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  introductionSidebar: [{type: 'autogenerated', dirName: 'introduction'}],
  eftSidebar: [
    'eft-turkish-banks/intro',
    'eft-turkish-banks/eft-flow',
    'eft-turkish-banks/create-eft',
    'eft-turkish-banks/check-eft-status',
    'eft-turkish-banks/get-eft-list',
    'eft-turkish-banks/get-refund-list',
    'eft-turkish-banks/cancel-eft',
    'eft-turkish-banks/webhooks',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'eft-turkish-banks/exchange',
    'eft-turkish-banks/validate-iban',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'eft-turkish-banks/error-codes',
  ],
  qrPaymentsSidebar: [
    'qr-payments/intro',
    'qr-payments/read-qr',
    'qr-payments/confirm-payment',
    'qr-payments/webhooks',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'qr-payments/mock-api',
  ],
  moneyTransfersSidebar: [
    'money-transfers/intro',
    {
      type: 'category',
      label: 'To Name (Cash Pick Up)',
      link: {
        type: 'generated-index',
        description: 'Send money that can be collected in cash from PayPorter offices or partner locations.',
      },
      items: [
        'money-transfers/to-name/overview',
        'money-transfers/to-name/find-firm',
        'money-transfers/to-name/find-city',
        'money-transfers/to-name/find-office',
        'money-transfers/to-name/validate',
        'money-transfers/to-name/confirm',
        'money-transfers/to-name/update',
        'money-transfers/to-name/cancel',
      ],
    },
    {
      type: 'category',
      label: 'To Bank Account',
      link: {
        type: 'generated-index',
        description: 'Direct transfer to a bank account or IBAN.',
      },
      items: [
        'money-transfers/to-account/overview',
        'money-transfers/to-account/find-bank',
        'money-transfers/to-account/validate',
        'money-transfers/to-account/confirm',
      ],
    },
    {
      type: 'category',
      label: 'To Wallet',
      link: {
        type: 'generated-index',
        description: 'Send funds to a recipient\'s electronic wallet.',
      },
      items: [
        'money-transfers/to-wallet/overview',
        'money-transfers/to-wallet/wallet-list',
        'money-transfers/to-wallet/get-holder',
        'money-transfers/to-wallet/validate',
        'money-transfers/to-wallet/confirm',
      ],
    },
    {
      type: 'category',
      label: 'To Card',
      link: {
        type: 'generated-index',
        description: 'Transfer directly to a debit or credit card.',
      },
      items: [
        'money-transfers/to-card/overview',
        'money-transfers/to-card/validate',
        'money-transfers/to-card/confirm',
      ],
    },
    'money-transfers/transfer-details',
    'money-transfers/transfer-errors',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    {
      type: 'category',
      label: 'Payment (Incoming Transfers)',
      link: {
        type: 'generated-index',
        description: 'Process incoming transfers using a reference number for payout.',
      },
      items: [
        'payments/overview',
        'payments/firm-list',
        'payments/search',
        'payments/validate',
        'payments/confirm',
        'payments/details',
      ],
    },
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    {
      type: 'category',
      label: 'Resources',
      link: {
        type: 'generated-index',
        description: 'Shared resources and reference data used across all transfer and payment types.',
      },
      items: [
        'resources/person-object',
        'resources/commons/identity-type-list',
        'resources/commons/job-list',
        'resources/commons/purpose-list',
        'resources/commons/source-of-income-list',
        'resources/commons/relationship-with-sender',
      ],
    },
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'money-transfers/fields-api',
  ],
  whitelabelWalletSidebar: [
    'whitelabel-wallet/intro',
    'whitelabel-wallet/authentication',
    'whitelabel-wallet/registration',
    'whitelabel-wallet/wallet-info',
    'whitelabel-wallet/transactions',
    {
      type: 'category',
      label: 'Money Transfers',
      items: [
        'whitelabel-wallet/transfers',
        'whitelabel-wallet/eft',
      ],
    },
    {
      type: 'category',
      label: 'Deposits & Withdrawals',
      items: [
        'whitelabel-wallet/deposits-withdrawals',
      ],
    },
    {
      type: 'category',
      label: 'KYC Verification',
      items: [
        'whitelabel-wallet/kyc-overview',
        'whitelabel-wallet/kyc-manual',
        'whitelabel-wallet/kyc-digital',
      ],
    },
    'whitelabel-wallet/card-operations',
    'whitelabel-wallet/webhooks',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
