import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  introductionSidebar: [{type: 'autogenerated', dirName: 'introduction'}],
  eftSidebar: [
    'eft-turkish-banks/intro',
    'eft-turkish-banks/eft-flow',
    'eft-turkish-banks/create-eft',
    'eft-turkish-banks/check-eft-status',
    'eft-turkish-banks/get-eft-list',
    'eft-turkish-banks/get-refund-list',
    'eft-turkish-banks/cancel-eft',
    'eft-turkish-banks/webhooks',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'eft-turkish-banks/exchange',
    'eft-turkish-banks/validate-iban',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'eft-turkish-banks/error-codes',
  ],
  qrPaymentsSidebar: [
    'qr-payments/intro',
    'qr-payments/read-qr',
    'qr-payments/confirm-payment',
    'qr-payments/webhooks',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-toc-border-color); margin: 15px 0; opacity: 0.5;" />',
    },
    'qr-payments/mock-api',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
